user: tiops
tidb_version: v3.0.12
topology:
  global:
    user: tiops
    ssh_port: 9999
    deploy_dir: /home/tiopsimport/ansible-deploy
    data_dir: data
    os: linux
    arch: amd64
  monitored:
    node_exporter_port: 9101
    blackbox_exporter_port: 9115
    deploy_dir: /home/tiopsimport/ansible-deploy
    data_dir: /home/tiopsimport/ansible-deploy/data
    log_dir: /home/tiopsimport/ansible-deploy/log
  server_configs:
    tidb:
      binlog.enable: true
    tikv: {}
    pd: {}
    tiflash: {}
    tiflash-learner: {}
    pump: {}
    drainer: {}
    cdc: {}
  tidb_servers:
    - host: 172.16.1.218
      ssh_port: 9999
      imported: true
      port: 4000
      status_port: 3399
      deploy_dir: /home/tiopsimport/ansible-deploy/tidb-4000
      arch: amd64
      os: linux
    - host: 172.16.1.219
      ssh_port: 2222
      imported: true
      port: 3397
      status_port: 10080
      deploy_dir: /home/tiopsimport/ansible-deploy/tidb-3397
      arch: amd64
      os: linux
  tikv_servers:
    - host: 172.16.1.219
      ssh_port: 2222
      imported: true
      port: 20160
      status_port: 20180
      deploy_dir: /home/tiopsimport/ansible-deploy/tikv-20160
      data_dir: data/tikv-20160
      arch: amd64
      os: linux
    - host: 172.16.1.220
      ssh_port: 9999
      imported: true
      port: 20166
      status_port: 20180
      deploy_dir: /home/tiopsimport/ansible-deploy/tikv-20166
      data_dir: data/tikv-20166
      arch: amd64
      os: linux
    - host: 172.16.1.221
      ssh_port: 9999
      imported: true
      port: 20160
      status_port: 20180
      deploy_dir: /home/tiopsimport/ansible-deploy/tikv-20160
      data_dir: data/tikv-20160
      arch: amd64
      os: linux
  tiflash_servers:
    - host: 172.16.1.222
      ssh_port: 9999
      imported: true
      tcp_port: 9000
      http_port: 8123
      flash_service_port: 3930
      flash_proxy_port: 20170
      flash_proxy_status_port: 20292
      metrics_port: 8234
      deploy_dir: /home/tiopsimport/ansible-deploy/tiflash-9000
      data_dir: data/tiflash-9000
      arch: amd64
      os: linux
    - host: 172.16.1.223
      ssh_port: 30000
      imported: true
      tcp_port: 9000
      http_port: 8123
      flash_service_port: 3930
      flash_proxy_port: 20170
      flash_proxy_status_port: 20292
      metrics_port: 8234
      deploy_dir: /home/tiopsimport/ansible-deploy/tiflash-9000
      data_dir: data/tiflash-9000
      arch: amd64
      os: linux
  pd_servers:
    - host: 172.16.1.218
      ssh_port: 30000
      imported: true
      name: TiDB-PD-218
      client_port: 2379
      peer_port: 2380
      deploy_dir: /home/tiopsimport/ansible-deploy/pd-2379
      data_dir: data/pd-2379
      arch: amd64
      os: linux
    - host: 172.16.1.219
      ssh_port: 2222
      imported: true
      name: pd-172.16.1.219-2379
      client_port: 2379
      peer_port: 2380
      deploy_dir: /home/tiopsimport/ansible-deploy/pd-2379
      data_dir: data/pd-2379
      arch: amd64
      os: linux
    - host: 172.16.1.220
      ssh_port: 9999
      imported: true
      name: pd-172.16.1.220-2379
      client_port: 2379
      peer_port: 2380
      deploy_dir: /home/tiopsimport/ansible-deploy/pd-2379
      data_dir: data/pd-2379
      arch: amd64
      os: linux
  pump_servers:
    - host: 172.16.1.219
      ssh_port: 2222
      imported: true
      port: 8250
      deploy_dir: /home/tiopsimport/ansible-deploy/pump-8250
      data_dir: data/pump-8250
      arch: amd64
      os: linux
    - host: 172.16.1.220
      ssh_port: 9999
      imported: true
      port: 8333
      deploy_dir: /home/tiopsimport/ansible-deploy/pump-8333
      data_dir: data/pump-8333
      arch: amd64
      os: linux
  drainer_servers:
    - host: 172.16.1.220
      ssh_port: 9999
      imported: true
      port: 8444
      deploy_dir: /home/tiopsimport/ansible-deploy/drainer-8444
      data_dir: data/drainer-8444
      arch: amd64
      os: linux
    - host: 172.16.1.221
      ssh_port: 9999
      imported: true
      port: 8249
      deploy_dir: /home/tiopsimport/ansible-deploy/drainer-8249
      data_dir: data/drainer-8249
      arch: amd64
      os: linux
  monitoring_servers:
    - host: 172.16.1.221
      ssh_port: 9999
      imported: true
      port: 9090
      deploy_dir: /home/tiopsimport/ansible-deploy/prometheus-9090
      data_dir: data/prometheus-9090
      storage_retention: 30d
      arch: amd64
      os: linux
  grafana_servers:
    - host: 172.16.1.221
      ssh_port: 9999
      imported: true
      port: 3000
      username: foo
      password: bar
      deploy_dir: /home/tiopsimport/ansible-deploy/grafana-3000
      arch: amd64
      os: linux
  alertmanager_servers:
    - host: 172.16.1.221
      ssh_port: 9999
      imported: true
      web_port: 9093
      cluster_port: 9094
      deploy_dir: /home/tiopsimport/ansible-deploy/alertmanager-9093
      data_dir: data/alertmanager-9093
      arch: amd64
      os: linux
