load "#{File.dirname(__FILE__)}/../_shared/Vagrantfile.partial.pubKey.rb"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4 * 1024
    v.cpus = 2
  end

  config.vm.network "private_network", ip: "10.0.1.20"
end
