---
# Variables here are applicable to all host groups
deploy_user: "{{ ansible_user }}"
status_dir: "{{ deploy_dir }}/status"
backup_dir: "{{ deploy_dir }}/backup"
images_dir: "{{ deploy_dir }}/images"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
fetch_tmp_dir: "{{ playbook_dir }}/collect_diagnosis_data"
fetch_dir: "{{ playbook_dir }}/collect_diagnosis"
cert_dir: "{{ playbook_dir }}/conf/ssl"
script_dir: "{{ playbook_dir }}/scripts"
binary_dir: "{{ playbook_dir }}/resources/bin"

# default configuration for multiple host groups and roles
node_exporter_port: 9101
blackbox_exporter_port: 9115
kafka_exporter_port: 9308

# docker
docker_bin_dir: "/usr/bin"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5

# deployment methods, [binary, docker] docker deployment method is not recommended and deprecated.
deployment_method: binary

enable_log_clean: False
log_retain_days: 28

dev_mode: True

# systemd: Specifies whether to send SIGKILL to remaining processes after a timeout.
disable_send_sigkill: False

# pump
pump_port: 8250
pump_data_dir: "{{ deploy_dir }}/data.pump"
pump_log_dir: "{{ deploy_dir }}/log"
pump_cert_dir: "{{ deploy_dir }}/conf/ssl"

# drainer
drainer_port: 8249
